# Numpy

Numpy is fundamental library for scientific computing in Python. It provides support for arrays and matrices along with a collection mathmetical functions to operate on these data structures. In this lessons, we will cover the basics of Numpy, focusing on arrays and vectorized operations.

In [1]:
import numpy as np

In [2]:
## Create array using numpy

## Create a 1D array

arr1 = np.array([1,2,3,4,5,6,7])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>
(7,)


In [3]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [4]:
# 2D array
arr2 = np.array([[1,2,3,4],[3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4]
 [3 4 5 6]]
(2, 4)


In [5]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [6]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
# Identity matrix

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
# Attributes of numpy array

arr = np.array([[1,2,3],[4,5,6],[6,7,8]])

print("Array:\n", arr)
print("Shape:", arr.shape)
print("Number of dimensions:", arr.ndim)
print("Size (total number of elements):", arr.size)
print("Data Type:", arr.dtype)
print("Item size (in bytes):", arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]
 [6 7 8]]
Shape: (3, 3)
Number of dimensions: 2
Size (total number of elements): 9
Data Type: int64
Item size (in bytes): 8


In [12]:
## Numpy Vectorized OPerations
a = np.array([1,2,3,4])
b = np.array([10,20,30,40])


## Element wise addition
print("Addition:", a+b)

## Element wise subtraction
print("Subtraction:", b-a)

## Element wise multiplication
print("Multiplication:", a*b)

## Element wise division
print("Division:", a/b)





Addition: [11 22 33 44]
Subtraction: [ 9 18 27 36]
Multiplication: [ 10  40  90 160]
Division: [0.1 0.1 0.1 0.1]


In [13]:
# Universal Functions 

## Square root
print("Square root:", np.sqrt(a))

## Exponential function
print("Exponential:", np.exp(a))

## Sine function
print("Sine:", np.sin(a))

## Logarithm
print("Logarithm:", np.log(a))

Square root: [1.         1.41421356 1.73205081 2.        ]
Exponential: [ 2.71828183  7.3890561  20.08553692 54.59815003]
Sine: [ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
Logarithm: [0.         0.69314718 1.09861229 1.38629436]


In [14]:
## array slicing and indexing

a = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])

print("Original Array:\n", a)

Original Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [15]:
a[0]

array([1, 2, 3, 4, 5])

In [16]:
a[0][0]

np.int64(1)

In [18]:
a[1:]

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [17]:
a[1:, 2:]

array([[ 8,  9, 10],
       [13, 14, 15]])

In [36]:
print(a[0:2])
print(a[0:2, 3:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 4  5]
 [ 9 10]]


In [37]:
## Modify array elements

a[0,0] = 100
a[0,1] = 99

print(a)

[[100  99   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]]


In [38]:
a[1:] = 100

print(a)

[[100  99   3   4   5]
 [100 100 100 100 100]
 [100 100 100 100 100]]


In [ ]:
## Statistical concepts -- Normalization

## To have a mean of 0 and standard deviation of 1
data = np.array([1,2,3,4,5])

# Calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
normalized_data = (data - mean) / std_dev
print("Normalized Data:", normalized_data)




Normalized Data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [40]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

# Mean
mean = np.mean(data)
print("Mean: ", mean)

# Median
median = np.median(data)
print("Median: ", median)

# Standard Deviation
std_dev = np.std(data)
print("Standard Deviation: ", std_dev)

# Variance
variance = np.var(data)
print("Variance: ", variance)


Mean:  5.5
Median:  5.5
Standard Deviation:  2.8722813232690143
Variance:  8.25


In [ ]:
## Logical Operations

data = np.array([1,2,3,4,5,6,7,8,9,10])

data>5


array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [42]:
data[data>5]

array([ 6,  7,  8,  9, 10])

In [44]:
data[(data>3) & (data<8)]

array([4, 5, 6, 7])